### ISSUE TITLE
Could not open video.

### ISSUE THREAD

**Issue by bill753852** [citrusvanilla/multiplewavetracking_py#4]
[ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-u4kjpz2z\opencv\modules\videoio\src\cap.cpp (162) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-u4kjpz2z\opencv\modules\videoio\src\cap_images.cpp:293: error: (-215:Assertion failed) !_filename.empty() in function 'cv::CvCapture_Images::open'

sorry I am a beginner，i dont no why i can't open the video

**Comment by citrusvanilla** [comment]
How are you invoking the executable?  It should be: `python3 mwt.py -i <your_file>`

**Comment by bill753852** [comment]
thank for your help!! I can run the program

**Comment by bill753852** [comment]
I use your built-in video but this situation
Program performance: 37.4 frames per second.
Wave #{}: ID: {}, Birth: {}, Death: {}, Max Displacement: {}, Max Mass: {}
Traceback (most recent call last):
  File "mwt.py", line 232, in <module>
    main(sys.argv[1:])
  File "mwt.py", line 218, in main
    recognized_waves, wave_log, program_speed = analyze(inputvideo,
  File "mwt.py", line 180, in analyze
    print ("Wave #{}: ID: {}, Birth: {}, Death: {}," \
AttributeError: 'NoneType' object has no attribute 'format'
No statistics the Wave #{}: ID: {}, Birth: {}, Death: {}, Max Displacement: {}, Max Mass: {}

**Comment by mattl98** [comment]
Hi! Also a beginner with a similar issue. I'm not getting any wave statistics. 

multiplewavetracking_py % python3 mwt.py -i /Users/matt.leung/Documents/ASE/WaveTrackingRepo/multiplewavetracking_py/scenes/scene1.mp4
Checking video from /Users/matt.leung/Documents/ASE/WaveTrackingRepo/multiplewavetracking_py/scenes/scene1.mp4
Starting analysis of 1367 frames...
.........100.........200.........300.........400.........500.........600.........700.........800.........900.........1000.........1100.........1200.........1300......End of video reached successfully.
4 wave(s) recognized.
Program performance: 36.8 frames per second.
Wave #{}: ID: {}, Birth: {}, Death: {}, Max Displacement: {}, Max Mass: {}
Traceback (most recent call last):
  File "/Users/matt.leung/Documents/ASE/WaveTrackingRepo/multiplewavetracking_py/mwt.py", line 232, in <module>
    main(sys.argv[1:])
  File "/Users/matt.leung/Documents/ASE/WaveTrackingRepo/multiplewavetracking_py/mwt.py", line 218, in main
    recognized_waves, wave_log, program_speed = analyze(inputvideo,
  File "/Users/matt.leung/Documents/ASE/WaveTrackingRepo/multiplewavetracking_py/mwt.py", line 180, in analyze
    print ("Wave #{}: ID: {}, Birth: {}, Death: {}," \
AttributeError: 'NoneType' object has no attribute 'format'

**Comment by mattl98** [comment]
Also, previously I could also not read video. But upon typing "-i" after mwt.py it worked. What is the "-i", what does it do, and why did that fix it?

**Comment by citrusvanilla** [comment]
@mattl98 

sorry, i havent maintained this project.  `-i` is a command line arg in this program meaning 'input' and whatever comes after that is the file.  its on line 200 of mwt.py.

the exception you are seeing, `attribute error: ...` is a bug on my part, but basically it is saying the program did not find any waves in your video

**Comment by mattl98** [comment]
Thanks for the info! Regardless, it was able to output a video and detect waves in that output mp4. Really impressed!

I'm interested in using this model to take live video inputs of a surf break, detect when waves are present, and somehow configure notifications to be sent via text or email when those waves are present. 

Is this feasible with your model?

**Comment by citrusvanilla** [comment]
Oh huh that's surprising to me.  You might have to send me the video so I can reproduce this bug and fix it.  Please email me at @justincaseyfung@gmail.com. 

Yes that would be feasible but it'll require you to have a working knowledge of a cloud application.  Kind of a lot to learn.  You'll need to host this program on a server in the cloud, and stream in your video somehow.

**Comment by mattl98** [comment]
Done! This is something I'm passionate about so I'm happy to learn :)

**Comment by citrusvanilla** [comment]
This is fixed with the latest commit.  I've updated everything to run on python 3.10.
